# Generated by Django 3.0.3 on 2020-07-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Satmak', 'Satmak'), ('Satın Almak', 'Satın Almak'), ('Kiraya Vermek', 'Kiraya Vermek'), ('Kiralamak', 'Kiralamak'), ('Gayrimenkul Değerlemesi', 'Gayrimenkul Değerlemesi'), ('Arsa Yatırımı', 'Arsa Yatırımı'), ('Diğer', 'Diğer'), ('Talebiniz', 'Talebiniz')], default='Talebiniz', max_length=25)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('closed', 'Closed')], default='new', max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
