# Generated by Django 3.0.5 on 2020-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200806_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Anahtar Teslim Web Sitesi', 'Anahtar Teslim Web Sitesi'), ('HTML5 CSS3', 'HTML5 CSS3'), ('SEO Uygulaması', 'SEO Uygulaması'), ('Size Özel Tema', 'Size Özel Tema'), ('Diğer', 'Diğer'), ('Talebiniz', 'Talebiniz')], default='Talebiniz', max_length=50),
        ),
    ]
